import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import pg from 'pg';import {randomUUID} from 'node:crypto';import {databaseOptions} from '../server/auth/database.js';import {assertDevelopment} from '../scripts/rc-v3-development-guard.mjs';import {inspect,schemaShape} from '../maintenance/fax-v3-production/schema.mjs';import {HASHES} from '../maintenance/fax-v3-production/policy.mjs';
test('Production preflight schema inspector: disposable Development fixtures, drift/ledger/auth conflicts',{skip:process.env.RC_V3_DB_TEST!=='1'},async()=>{
 assertDevelopment(process.env);const suffix=randomUUID().replaceAll('-',''),auth='prep_auth_'+suffix,schema='prep_rc_'+suffix;const c=new pg.Client(databaseOptions());c.on('error',()=>{});const expected=JSON.parse(await readFile(new URL('../maintenance/fax-v3-production/schema-expected.json',import.meta.url),'utf8'));
 try{await c.connect();await c.query('BEGIN');await c.query('SET LOCAL search_path=pg_catalog');const sql=async name=>(await readFile(new URL('../migrations/'+name+'.sql',import.meta.url),'utf8')).replaceAll('toolkit_auth',auth).replaceAll('toolkit_rc_v3',schema);await c.query(await sql('001_toolkit_auth'));await c.query(`CREATE TABLE ${auth}.migrations(name text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now())`);await c.query(`INSERT INTO ${auth}.migrations(name,checksum) VALUES($1,$2)`,['001_toolkit_auth',HASHES['001_toolkit_auth']]);const identity={database:(await c.query('SELECT current_database() AS database')).rows[0].database};const check=stage=>inspect(c,identity,expected,stage,{auth,schema});await check(0);
  await c.query(`UPDATE ${auth}.migrations SET checksum='wrong'`);await assert.rejects(check(0));await c.query(`UPDATE ${auth}.migrations SET checksum=$1`,[HASHES['001_toolkit_auth']]);
  await c.query(`CREATE SCHEMA ${schema}`);await assert.rejects(check(0));await c.query(`DROP SCHEMA ${schema}`);
  await c.query(`ALTER TABLE ${auth}.users ADD COLUMN unexpected text`);await assert.rejects(check(0));await c.query(`ALTER TABLE ${auth}.users DROP COLUMN unexpected`);await check(0);
  for(const [name,stage]of [['002_ringcentral_v3',2],['003_fax_v3_operations',3]]){await c.query(await sql(name));await c.query(`INSERT INTO ${auth}.migrations(name,checksum) VALUES($1,$2)`,[name,HASHES[name]]);await check(stage);await assert.rejects(check(0));assert.deepEqual(await schemaShape(c,schema,auth),expected[String(stage)]);}
  await c.query(`ALTER TABLE ${schema}.fax_attempts DROP CONSTRAINT fax_single_retry`);await assert.rejects(check(3));
 }finally{await c.query('ROLLBACK').catch(()=>{});await c.end();}
});
