import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join,dirname,resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
const browserPath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
const pause=ms=>new Promise(r=>setTimeout(r,ms));
test('Fax v3 desktop/mobile: responsive polish, connection placement, contacts, batches, receipts, history and employee changes',{skip:!browserPath,timeout:90000},async t=>{
  let employee='A',signedIn=true,connectionState='connected',connectionFailure=false,sendCount=0,receiptCount=0,holdSend=false,releaseSend,holdContacts=false,releaseContacts,holdSession=false,releaseSession;
  const histories={A:[],B:[]},requests=[],receiptIds=[],coverSubmissions=[];
  const server=createServer(async(req,res)=>{
    const path=req.url.split('?')[0];res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');
    if(path==='/api/auth/session'){if(holdSession)await new Promise(r=>releaseSession=r);res.statusCode=signedIn?200:401;return res.end(JSON.stringify(signedIn?{authenticated:true,user:{displayName:'Employee '+employee}}:{authenticated:false}));}
    if(path==='/api/auth/logout'){signedIn=false;return res.end('{}');}
    if(path==='/api/ringcentral/connection'){if(connectionFailure){res.statusCode=502;return res.end('{}');}return res.end(JSON.stringify({state:connectionState,displayName:'Employee '+employee,accountId:'827653020',extensionId:employee==='A'?'12345':'67890'}));}
    if(path==='/api/fax-v3/context'){res.statusCode=signedIn?200:401;return res.end(JSON.stringify({state:'connected',context:(employee==='A'?'a':'b').repeat(64)}));}
    if(path.startsWith('/api/fax-v3/')){
      const owner=employee;assert.equal(req.headers['x-toolkit-fax-context'],(owner==='A'?'a':'b').repeat(64));requests.push(path);
      if(path.endsWith('/history'))return res.end(JSON.stringify({entries:histories[owner].slice(0,20)}));
      if(path.endsWith('/contacts')){
        if(holdContacts)await new Promise(r=>releaseContacts=r);
        if(req.method==='POST')return res.end(JSON.stringify({contacts:{id:'2',name:'New Contact',numbers:['+442079460000']}}));
        return res.end(JSON.stringify({contacts:[{id:'1',name:'Contact '+owner,company:'',numbers:['+18015551234']}]}));
      }
      if(path.endsWith('/send')){
        sendCount++;const chunks=[];for await(const chunk of req)chunks.push(chunk);const form=await new Response(Buffer.concat(chunks),{headers:{'Content-Type':req.headers['content-type']}}).formData();
        assert.equal(form.get('fullSsn'),'123-45-6789');assert.equal(form.has('lastFour'),false);assert.equal(form.get('includeCoverSheet'),'true');assert.equal(form.getAll('file').length,1);coverSubmissions.push({filename:form.get('file').name,comment:form.get('coverPageText')});
        if(holdSend)await new Promise(r=>releaseSend=r);
        const entry={faxId:randomUUID(),batchId:form.get('batchId'),filename:form.get('file').name,lastFour:form.get('fullSsn').slice(-4),recipientName:form.get('recipientName'),faxNumber:form.get('faxNumber'),createdAt:new Date().toISOString(),status:'Sent',retryable:false,tracking:false,accessible:true};histories[owner].unshift(entry);return res.end(JSON.stringify(entry));
      }
      if(path.endsWith('/receipt')){receiptCount++;receiptIds.push(new URL(req.url,origin).searchParams.get('faxId'));res.setHeader('Content-Type','application/pdf');return res.end('%PDF-synthetic');}
      res.statusCode=404;return res.end('{}');
    }
    if(path.startsWith('/shared/')){
      const shared=path.slice('/shared/'.length);
      if(!['favicon.png','style.css','footer.css','settings-storage.js','app-shell.js','toolkit-auth.css','toolkit-auth.js'].includes(shared)){res.statusCode=404;return res.end();}
      res.setHeader('Content-Type',shared.endsWith('.js')?'text/javascript':shared.endsWith('.css')?'text/css':'image/png');return res.end(await readFile(new URL('../shared/'+shared,import.meta.url)));
    }
    const name=path==='/fax-sender/'?'index.html':path.split('/').pop();
    if(!['index.html','test.js','app.js','client.js','style.css'].includes(name)){res.statusCode=404;return res.end();}
    res.setHeader('Referrer-Policy','same-origin');res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(await readFile(new URL('../fax-sender/'+name,import.meta.url)));
  });
  await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));
  const origin='http://127.0.0.1:'+server.address().port;
  const profile=await mkdtemp(join(tmpdir(),'fax-v3-page-'));const files=[join(profile,'Brief.pdf'),join(profile,'Second.pdf')];for(const file of files)await writeFile(file,'%PDF-synthetic');
  const browser=spawn(browserPath,['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
  let socket;t.after(async()=>{releaseSend?.();releaseContacts?.();releaseSession?.();socket?.close();browser.kill();await pause(500);assert.equal(dirname(resolve(profile)),resolve(tmpdir()));await rm(profile,{recursive:true,force:true,maxRetries:10,retryDelay:200});});
  let port;for(let i=0;i<100&&!port;i++){port=await readFile(join(profile,'DevToolsActivePort'),'utf8').then(s=>s.split('\n')[0]).catch(()=>null);if(!port)await pause(100);}assert(port);
  const pages=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();socket=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await new Promise(r=>socket.onopen=r);
  const pending=new Map();let id=0;socket.onmessage=({data})=>{const e=JSON.parse(data);if(!pending.has(e.id))return;const p=pending.get(e.id);pending.delete(e.id);e.error?p.reject(Error('Browser protocol failed')):p.resolve(e.result);};
  const cdp=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const ev=async expression=>{const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});assert(!r.exceptionDetails);return r.result.value;};
  const until=async expression=>{for(let i=0;i<200;i++){if(await ev(expression))return;await pause(50);}assert.fail('Browser condition: '+expression);};
  await cdp('Page.enable');
  await cdp('Page.setDownloadBehavior',{behavior:'deny'});
  await cdp('Page.addScriptToEvaluateOnNewDocument',{source:"localStorage.setItem('packard.faxHistory.v1','PRIVATE LEGACY CANARY')"});
  const choose=async()=>{const {root}=await cdp('DOM.getDocument');const {nodeId}=await cdp('DOM.querySelector',{nodeId:root.nodeId,selector:'#pdfFiles'});await cdp('DOM.setFileInputFiles',{nodeId,files});await until("document.querySelectorAll('#documents li').length===2");};
  for(const width of [1280,390]){
    employee='A';signedIn=true;histories.A=[];histories.B=[];
    await cdp('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});await cdp('Page.navigate',{url:origin+'/fax-sender/'});
    await until("document.getElementById('faxWorkspace')&&!document.getElementById('faxWorkspace').hidden");assert(await ev("localStorage.getItem('packard.faxHistory.v1')==='PRIVATE LEGACY CANARY' && ![...Object.keys(localStorage)].some(key=>/fax-v3|ringcentral/i.test(key)) && sessionStorage.length===0 && !document.body.textContent.includes('PRIVATE LEGACY') && document.getElementById('accountId').hidden"));
    assert(await ev("document.getElementById('accountStatus').parentElement.id==='accountStatusBottom' && !document.getElementById('accountStatusBottom').hidden && !document.getElementById('identity').hidden && !document.getElementById('refresh').hidden && !document.getElementById('disconnect').hidden"),'Healthy connected status retains identity and secondary actions at page bottom');
    assert(await ev("(()=>{const d=document.querySelector('.destination-number-field').getBoundingClientRect(),s=document.querySelector('.full-ssn-field').getBoundingClientRect(),di=document.getElementById('destination').getBoundingClientRect(),si=document.getElementById('fullSsn').getBoundingClientRect(),a=document.querySelector('.field-actions').getBoundingClientRect(),g=document.querySelector('.destination-action-buttons').getBoundingClientRect(),c=document.querySelector('.cover-toggle').getBoundingClientRect(),r=document.querySelector('.destination-recipient-row').getBoundingClientRect();return innerWidth>=641?Math.abs(d.top-s.top)<1&&di.width>si.width*2&&si.width<=140&&a.top>=r.bottom-1&&Math.abs(a.left-r.left)<1&&Math.abs(g.top-c.top)<1&&c.left>=g.right:s.top>=d.bottom&&a.top>=r.bottom-1&&Math.abs(a.left-r.left)<1&&g.left===a.left&&c.top>=g.top&&c.right<=a.right+1})()"),'Destination, Full SSN, grouped destination actions, and cover toggle align and wrap responsively');
    assert(await ev("document.querySelector('.field-actions #cover') && document.getElementById('autofillComments').checked && !document.getElementById('comment') && document.getElementById('fullSsn').required && document.querySelector('.full-ssn-field label').textContent==='Full SSN' && !document.body.innerText.includes('Clearing the composer preserves this history.') && !document.body.innerText.includes('Used for history and receipt filenames only.')"),'Cover and autofill controls remain wired beside destination actions, with required Full SSN and no shared comment field');
    assert(await ev("(()=>{const t=document.body.innerText;return !['Choose a destination','US numbers may use 10 digits. International numbers need + and country code.','Up to 1,024 characters','Newest 20 attempts','New selections are added to the list','Retry is only available','Retry is available only','Send PDFs from your own RingCentral extension.'].some(s=>t.includes(s))})()"),'Requested helper copy is absent');
    const themes=await ev("(()=>{const root=document.documentElement,values={};for(const theme of ['light','dark','sepia','forest']){root.dataset.theme=theme;const style=getComputedStyle(root);values[theme]=style.getPropertyValue('--page-bg').trim();if(theme==='dark'&&style.colorScheme!=='dark')return null;}root.dataset.theme='light';return values})()");assert(themes,'Dark mode keeps its dark color scheme');assert.equal(new Set(Object.values(themes)).size,4,'All shared themes retain distinct Fax Sender page surfaces');
    if(width===1280){for(const state of ['disconnected','connecting','needs_reconnect','disconnecting']){connectionState=state;await ev("document.getElementById('refresh').click()");await until(`document.getElementById('connectionState').textContent==='${({disconnected:'Not connected. Connect your own RingCentral account.',connecting:'A connection attempt is pending. You can try Connect again or disconnect to cancel it.',needs_reconnect:'Reconnect required. Disconnect first, then connect your RingCentral account again.',disconnecting:'Disconnect is pending. Retry Disconnect to finish revoking access.'})[state]}'`);assert(await ev("document.getElementById('accountStatus').parentElement.id==='accountStatusTop' && document.getElementById('accountStatusBottom').hidden"),`${state} connection remains prominent`);}connectionState='connected';await ev("document.getElementById('refresh').click()");await until("document.getElementById('accountStatus').parentElement.id==='accountStatusBottom'");connectionFailure=true;await ev("document.getElementById('refresh').click()");await until("document.getElementById('toolkitState').textContent==='Toolkit sign-in is unavailable or has changed.'");assert(await ev("document.getElementById('accountStatus').parentElement.id==='accountStatusTop' && document.getElementById('signIn').getClientRects().length>0"),'Connection errors and required sign-in remain prominent');connectionFailure=false;await ev("document.getElementById('refresh').click()");await until("document.getElementById('accountStatus').parentElement.id==='accountStatusBottom'");}
    if(width===1280){
      holdSession=true;await ev("window.dispatchEvent(new Event('focus'))");for(let i=0;i<100&&!releaseSession;i++)await pause(20);assert(releaseSession);
      assert(await ev("document.getElementById('toolkitState').textContent==='Signed in as Employee A' && !document.getElementById('identity').hidden && !document.getElementById('faxWorkspace').hidden"));
      holdSession=false;const release=releaseSession;releaseSession=null;release();await pause(150);
      const queued={faxId:randomUUID(),filename:'Existing.pdf',lastFour:'0012',recipientName:'Controlled recipient',faxNumber:'+18015551234',createdAt:new Date().toISOString(),status:'Queued',retryable:false,tracking:true,accessible:true};histories.A=[queued];const beforePoll=sendCount;
      await cdp('Page.reload');await until("document.querySelectorAll('#faxHistory li').length===1");await until("document.getElementById('faxNotice').textContent.includes('Fax status could not be refreshed')");
      assert.equal(sendCount,beforePoll);assert.equal(histories.A[0].status,'Queued');assert.equal(histories.A[0].retryable,false);
      histories.A=[];await cdp('Page.reload');await until("document.querySelectorAll('#faxHistory li').length===0 && !document.getElementById('faxWorkspace').hidden");
    }
    await ev("document.getElementById('loadContacts').click()");await pause(200);assert.equal(await ev("document.getElementById('contactNotice').textContent"),'1 fax contacts loaded.');await until("document.querySelector('#contactResults button')");await ev("document.querySelector('#contactResults button').click()");
    assert.equal(await ev("document.getElementById('destination').value"),'+18015551234');
    await ev("document.getElementById('clearDestination').click()");assert(await ev("document.getElementById('destination').value==='' && document.activeElement.id==='destination'"));
    await ev("document.getElementById('destination').value='+18015551234';var ssn=document.getElementById('fullSsn');ssn.value='123x45678999';ssn.dispatchEvent(new Event('input'))");assert.equal(await ev("document.getElementById('fullSsn').value"),'123-45-6789','Full SSN formats and limits input to nine digits');
    await ev("document.getElementById('cover').click()");assert(await ev("!document.getElementById('cover').checked && document.getElementById('autofillControl').hidden && !document.querySelector('.document-comment:not([hidden])')"),'Turning cover sheets off hides autofill and leaves no comment panel spacing');await ev("document.getElementById('cover').click()");assert(await ev("!document.getElementById('autofillControl').hidden"),'Turning cover sheets on restores the autofill control');
    await choose();assert.equal(await ev("document.getElementById('documentCount').textContent"),'PDF documents (2)');assert.deepEqual(await ev("[...document.querySelectorAll('.document-comment textarea')].map(input=>input.value)"),['Brief for 123-45-6789','Second for 123-45-6789'],'Autofill uses each filename without the final PDF extension');
    const cardLayout=await ev("(()=>{const card=document.querySelector('#documents li'),r=e=>{const x=e.getBoundingClientRect();return {left:x.left,right:x.right,top:x.top,bottom:x.bottom,width:x.width,height:x.height}};return {width:innerWidth,card:r(card),info:r(card.querySelector('.document-info')),comment:r(card.querySelector('.document-comment')),controls:r(card.querySelector('.document-controls'))}})()");
    assert(width>=641?cardLayout.info.left<cardLayout.comment.left&&cardLayout.comment.left<cardLayout.controls.left&&cardLayout.comment.width>cardLayout.info.width&&cardLayout.card.height<=90:Math.abs(cardLayout.info.top-cardLayout.controls.top)<1&&cardLayout.comment.top>=cardLayout.info.bottom&&cardLayout.comment.width>cardLayout.card.width*.85&&cardLayout.card.height<=175,'Document card uses a compact three-column desktop layout and a usable stacked mobile layout: '+JSON.stringify(cardLayout));
    const cardBeforeCoverOff=await ev("(()=>{const card=document.querySelector('#documents li');return {height:card.getBoundingClientRect().height,info:card.querySelector('.document-info').getBoundingClientRect().width}})()");await ev("document.getElementById('cover').click()");assert(await ev("(()=>{const card=document.querySelector('#documents li'),comment=card.querySelector('.document-comment'),info=card.querySelector('.document-info');return comment.hidden&&getComputedStyle(comment).display==='none'&&"+(width>=641?"info.getBoundingClientRect().width>"+cardBeforeCoverOff.info:"card.getBoundingClientRect().height<"+cardBeforeCoverOff.height)+"})()"),'Cover sheet OFF removes the comment column and lets the remaining card layout use its space');await ev("document.getElementById('cover').click()");assert(await ev("!document.querySelector('.document-comment').hidden"),'Cover sheet ON restores the comment column');
    await ev("document.getElementById('autofillComments').click()");assert.deepEqual(await ev("[...document.querySelectorAll('.document-comment textarea')].map(input=>input.value)"),['Brief for 123-45-6789','Second for 123-45-6789'],'Turning autofill off preserves current comments');
    await ev("(()=>{const input=document.querySelector('.document-comment textarea');window.commentFocusProbe=input;input.focus();for(const value of ['F','Fi','Fir','First document note']){input.value=value;input.dispatchEvent(new Event('input'));}window.dispatchEvent(new CustomEvent('toolkit-rc-state',{detail:'connected'}));})()");await pause(250);assert(await ev("document.activeElement===window.commentFocusProbe && document.querySelector('.document-comment textarea')===window.commentFocusProbe && window.commentFocusProbe.value==='First document note'"),'Continuous typing retains the same focused textarea through background renders');
    await ev("var fields=[...document.querySelectorAll('.document-comment textarea')];fields[1].value='Second document note';fields[1].dispatchEvent(new Event('input'));[...document.querySelectorAll('#documents li:first-child .document-controls button')].find(b=>b.textContent==='Move down').click()");assert(await ev("document.activeElement===document.querySelectorAll('#documents li')[1]"));assert.deepEqual(await ev("[...document.querySelectorAll('#documents li')].map(li=>[li.querySelector('.document-title').textContent,li.querySelector('textarea').value])"),[['Second.pdf','Second document note'],['Brief.pdf','First document note']],'Reordering retains each document comment and restores card focus');
    await ev("document.querySelector('#documents li .document-controls button').click()");assert.equal(await ev("document.querySelectorAll('#documents li').length"),1,'PDF remove action updates the batch');await choose();assert.equal(await ev("document.querySelectorAll('#documents li').length"),2,'PDF selection can refill the batch');assert.deepEqual(await ev("[...document.querySelectorAll('#documents li')].map(li=>li.querySelector('textarea').value)"),['First document note','Second'],'Adding a PDF does not corrupt another manual comment');
    await ev("document.getElementById('autofillComments').click()");assert.deepEqual(await ev("[...document.querySelectorAll('.document-comment textarea')].map(input=>input.value)"),['Brief for 123-45-6789','Second for 123-45-6789'],'Turning autofill back on regenerates all comments');await ev("var ssn=document.getElementById('fullSsn');ssn.value='987654321';ssn.dispatchEvent(new Event('input'))");assert.deepEqual(await ev("[...document.querySelectorAll('.document-comment textarea')].map(input=>input.value)"),['Brief for 987-65-4321','Second for 987-65-4321'],'Changing Full SSN updates autofilled comments');await ev("var ssn=document.getElementById('fullSsn');ssn.value='123456789';ssn.dispatchEvent(new Event('input'));document.querySelectorAll('#documents li')[1].querySelector('button').click()");await choose();assert.equal(await ev("document.querySelectorAll('#documents li')[1].querySelector('textarea').value"),'Second for 123-45-6789','New PDFs autofill while enabled');
    assert(await ev("document.documentElement.scrollWidth<=innerWidth && document.querySelector('h1').textContent==='Fax Sender' && [...document.querySelectorAll('.document-comment textarea')].every(input=>input.getBoundingClientRect().height<=80)"),'Compact document cards fit without overflow');
    assert(await ev("(()=>{const root=document.documentElement,panel=document.querySelector('.composer-panel');root.dataset.theme='light';const light=getComputedStyle(panel).backgroundColor;root.dataset.theme='dark';return light!==getComputedStyle(panel).backgroundColor&&getComputedStyle(root).colorScheme==='dark'})()"));await ev("document.documentElement.dataset.theme='light'");
    const shot=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(join(tmpdir(),'fax-v3-polish-'+width+'.png'),Buffer.from(shot.data,'base64'));
    const before=sendCount;await ev("var ssn=document.getElementById('fullSsn');ssn.value='12345678';ssn.dispatchEvent(new Event('input'));document.getElementById('send').click()");await pause(150);assert.equal(sendCount,before);
    await ev("var ssn=document.getElementById('fullSsn');ssn.value='123456789';ssn.dispatchEvent(new Event('input'));document.getElementById('autofillComments').click();var fields=[...document.querySelectorAll('.document-comment textarea')];fields[0].value='First document note';fields[0].dispatchEvent(new Event('input'));fields[1].value='Second document note';fields[1].dispatchEvent(new Event('input'));document.getElementById('send').click()");
    await until("document.querySelectorAll('#faxHistory li').length===2 && document.getElementById('progress').textContent===''");assert.equal(sendCount,before+2);
    assert(await ev("[...document.querySelectorAll('#documents li')].every(li=>{const button=[...li.querySelectorAll('.document-controls button')].find(button=>button.textContent==='Download Fax Receipt'),card=li.getBoundingClientRect(),control=button?.getBoundingClientRect();return li.dataset.state==='Sent'&&button&&control.right<=card.right-4&&control.bottom<=card.bottom-4})"),'Sent document cards retain status and visible, contained individual receipt controls');
    assert.deepEqual(coverSubmissions.slice(-2),[{filename:'Brief.pdf',comment:'First document note'},{filename:'Second.pdf',comment:'Second document note'}],'Each fax in one batch submits its own cover-sheet comment');
    assert(histories.A.every(entry=>entry.lastFour==='6789')&&!JSON.stringify(histories.A).includes('123-45-6789'),'History retains only derived Last 4 and never the Full SSN');
    assert(await ev("document.getElementById('destination').disabled && document.getElementById('fullSsn').disabled && !document.querySelector('#faxHistory details[open]') && document.querySelectorAll('#faxHistory .status.sent').length===2"));
    const historyShot=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(join(tmpdir(),'fax-v3-polish-history-'+width+'.png'),Buffer.from(historyShot.data,'base64'));
    const firstBatch=histories.A[0].batchId;assert(firstBatch);assert.equal(new Set(histories.A.slice(0,2).map(entry=>entry.batchId)).size,1,'One send run shares one batch ID');
    await ev("document.getElementById('clear').click()");await until("document.querySelectorAll('#documents li').length===0");await choose();await ev("document.getElementById('destination').value='+18015551234';var ssn=document.getElementById('fullSsn');ssn.value='123456789';ssn.dispatchEvent(new Event('input'));document.getElementById('send').click()");await until("document.querySelectorAll('#faxHistory li').length===4 && document.getElementById('progress').textContent==='' ");
    const newestBatch=histories.A[0].batchId;assert(newestBatch);assert.notEqual(newestBatch,firstBatch,'Separate send runs receive different batch IDs');assert.equal(new Set(histories.A.slice(0,2).map(entry=>entry.batchId)).size,1);
    histories.A[0]={...histories.A[0],status:'SendingFailed',retryable:true};await cdp('Page.reload');await until("document.querySelectorAll('#faxHistory li').length===4 && document.querySelectorAll('#faxHistory .status.failed').length===1 && document.querySelectorAll('#faxHistory .status.sent').length===3 && !document.getElementById('downloadAll').disabled");
    const beforeRecent=receiptIds.length;await ev("document.getElementById('downloadAll').click()");await until("document.getElementById('receiptNotice').textContent.includes('1 receipt(s)')");assert.deepEqual(receiptIds.slice(beforeRecent),[histories.A[1].faxId],'Download all receipts selects only Sent receipts in the newest batch');
    const beforeZip=receiptIds.length;await ev("document.getElementById('downloadZip').click()");await until("document.getElementById('receiptNotice').textContent.includes('3 receipt(s)')");assert.deepEqual(new Set(receiptIds.slice(beforeZip)),new Set(histories.A.filter(entry=>entry.status==='Sent').map(entry=>entry.faxId)),'Download ZIP still includes all available Sent history receipts');
    await ev("document.getElementById('clear').click()");await until("document.querySelectorAll('#documents li').length===0");assert.equal(await ev("document.querySelectorAll('#faxHistory li').length"),4);
    await ev("document.getElementById('destination').value='+442079460000';document.getElementById('contactName').value='New Contact';document.getElementById('createContact').click()");await until("document.getElementById('contactNotice').textContent==='Contact saved and selected.'");
    await cdp('Page.reload');await until("document.querySelectorAll('#faxHistory li').length===4 && document.querySelectorAll('#faxHistory .status.sent').length===3 && !document.getElementById('loadContacts').disabled && !document.getElementById('downloadAll').disabled");const beforeReloadedBatch=receiptIds.length;await ev("document.getElementById('downloadAll').click()");await until("document.getElementById('receiptNotice').textContent.includes('1 receipt(s)')");assert.deepEqual(receiptIds.slice(beforeReloadedBatch),[histories.A[1].faxId],'Reloaded history preserves newest-batch grouping');
    holdContacts=true;await ev("document.getElementById('loadContacts').click()");for(let i=0;i<100&&!releaseContacts;i++)await pause(20);assert(releaseContacts);
    employee='B';await ev("document.getElementById('refresh').click()");await until("document.getElementById('toolkitState').textContent==='Signed in as Employee B' && document.querySelectorAll('#faxHistory li').length===0");holdContacts=false;releaseContacts();releaseContacts=null;await pause(150);
    assert(await ev("!document.getElementById('contactResults').textContent.includes('Contact A') && document.querySelectorAll('#documents li').length===0 && document.documentElement.scrollWidth<=innerWidth"));
    await choose();holdSend=true;const n=sendCount;await ev("document.getElementById('destination').value='+18015551234';var ssn=document.getElementById('fullSsn');ssn.value='123456789';ssn.dispatchEvent(new Event('input'));document.getElementById('send').click()");
    for(let i=0;i<100&&!releaseSend;i++)await pause(20);assert(releaseSend);await ev("document.getElementById('signOut').click()");await until("document.getElementById('faxWorkspace').hidden");holdSend=false;releaseSend();releaseSend=null;await pause(1200);assert.equal(sendCount,n+1);
    assert(await ev("document.querySelectorAll('#documents li').length===0 && document.querySelectorAll('#faxHistory li').length===0 && document.getElementById('accountStatus').parentElement.id==='accountStatusTop' && localStorage.getItem('packard.faxHistory.v1')==='PRIVATE LEGACY CANARY' && ![...Object.keys(localStorage)].some(key=>/fax-v3|ringcentral/i.test(key)) && sessionStorage.length===0"));
  }
  assert(requests.every(path=>path.startsWith('/api/fax-v3/')&&!path.includes('123-45-6789')),'Full SSN is absent from URLs and request identifiers');
});
