// Intentionally fictional, fixed data. No import, paste, upload or messaging channel.
import { schemaVersion } from './mapping.js';

export function syntheticProfile() {
  const values = [
    ['personal.first-name', 'Synthetic', 'text'],
    ['personal.last-name', 'Example', 'text'],
    ['personal.middle-name', null, 'text'],
    ['personal.suffix', 'Example', 'text'],
    ['personal.nickname', 'Sample', 'text'],
    ['personal.gender', 'Female', 'text'],
    ['medical-information.blindorhavelowvision', true, 'boolean'],
    ['personal.social-security-number', '000-12-3456', 'text'],
    ['personal.phone-number', '202-555-0142', 'text'],
    ['personal.alternate-phone', '202-555-0143', 'text'],
    ['personal.secondary-phone', '202-555-0144', 'text'],
    ['personal.email', 'synthetic@example.invalid', 'text'],
    ['language.preferred-language', 'Example Language', 'text'],
    ['language.can-speak-and-understand-english', true, 'boolean'],
    ['language.can-read-simple-english-messages', false, 'boolean'],
    ['language.can-write-simple-english-messages', false, 'boolean'],
    ['language.can-read-simple-messages-in-preferred-language', true, 'boolean'],
    ['language.can-write-simple-messages-in-preferred-language', true, 'boolean'],
    ['security-questions.mother-first-name', 'Example', 'text'],
    ['security-questions.mother-maiden-name', 'Fiction', 'text'],
    ['security-questions.father-first-name', 'Sample', 'text'],
    ['security-questions.father-last-name', 'Example', 'text'],
    ['security-questions.other-legal-representative', null, 'text'],
    ['vitals.height-feet', '5', 'text'],
    ['vitals.height-inches', '8', 'text'],
    ['vitals.weight-pounds', '150', 'text'],
    ['other-names.other-first-name', 'Alternate', 'text'],
    ['other-names.other-last-name', 'Example', 'text'],
    ['spouse.first-name', 'Fictional', 'text', null, 'current-spouse'],
    ['spouse.last-name', 'Partner', 'text', null, 'current-spouse'],
    ['spouse.social-security-number', '000-98-7654', 'text', null, 'current-spouse'],
    ['spouse.age', '45', 'text', null, 'current-spouse'],
    ['spouse.marriage-date', '2010-01-02', 'date', 'day', 'current-spouse'],
    ['spouse.city-of-marriage', 'Example City', 'text', null, 'current-spouse'],
    ['spouse.state-of-marriage', 'EX', 'text', null, 'current-spouse'],
    ['spouse.type-of-marriage', 'Example Type', 'text', null, 'current-spouse'],
    ['children.first-name', 'Fictional', 'text', null, 'child-1'],
    ['children.last-name', 'Child', 'text', null, 'child-1'],
    ['birth.date-of-birth', '2000-01-02', 'date', 'day'],
    ['birth.city-of-birth', 'Example City', 'text'],
    ['birth.state-of-birth', 'Example State', 'text'],
    ['birth.country-of-birth', 'Example Country', 'text'],
    ['address.mailing-address-street-address', '123 Fictional Lane', 'text'],
    ['address.mailing-address-city', 'Sample City', 'text'],
    ['address.mailing-address-state', 'EX', 'text'],
    ['address.mailing-address-zipcode', '00000', 'text'],
    ['address.physical-address-street-address', '456 Fictional Avenue', 'text'],
    ['address.physical-address-street-address-2', 'Unit Example', 'text'],
    ['address.physical-address-city', 'Another City', 'text'],
    ['address.physical-address-state', 'FX', 'text'],
    ['address.physical-address-zipcode', '11111', 'text'],
    ['disability.onset-date-of-disability', '2020-03', 'date', 'month'],
    ['employment.when-did-you-last-work', '2020-02', 'date', 'month'],
    ['employment.worked-outside-united-states', true, 'boolean'],
    ['employment.eligible-for-foreign-ssi', false, 'boolean'],
    ['employment.foreign-ssi-country', 'Example Country', 'text'],
    ['jobs.job-title', 'Example Job Title', 'text', null, 'job-1'],
    ['jobs.employer', 'Example Company', 'text', null, 'job-1'],
    ['jobs.business-type', 'Example Business Type', 'text', null, 'job-1'],
    ['jobs.address', '123 Fictional Work Road', 'text', null, 'job-1'],
    ['jobs.city', 'Sample City', 'text', null, 'job-1'],
    ['jobs.state', 'EX', 'text', null, 'job-1'],
    ['jobs.zipcode', '00000', 'text', null, 'job-1'],
    ['jobs.hours-per-day', '8', 'text', null, 'job-1'],
    ['jobs.days-per-week', '5', 'text', null, 'job-1'],
    ['jobs.rate-of-pay', '$20.00', 'text', null, 'job-1'],
    ['jobs.pay-frequency', 'Weekly', 'text', null, 'job-1'],
    ['jobs.start-date', '2010-01-02', 'date', 'day', 'job-1'],
    ['jobs.end-date', '2015-06-07', 'date', 'day', 'job-1'],
  ];
  return { schema: 'packard.intake-client-profile', schemaVersion, priorSpouseRecords: [], jobRecords: ['job-1'],
    employmentQuestionFields: ['employment.worked-outside-united-states', 'employment.eligible-for-foreign-ssi', 'employment.foreign-ssi-country'],
    employmentQuestionMissingFields: [], fields: values.map(([definitionId, value, dataType, precision = null, recordId = null]) => ({
    id: recordId ? `${definitionId}@${recordId}` : definitionId, definitionId, recordId,
    value, dataType, precision, readiness: value === null ? 'blocked' : 'ready',
    blockingReasons: value === null ? [{ code: 'missing' }] : [],
  })) };
}
