// Intentionally fictional, fixed data. No import, paste, upload or messaging channel.
export function syntheticProfile() {
  const values = [
    ['personal.first-name', 'Synthetic', 'text'],
    ['personal.last-name', 'Example', 'text'],
    ['personal.middle-name', null, 'text'],
    ['personal.suffix', 'Example', 'text'],
    ['personal.nickname', 'Sample', 'text'],
    ['personal.gender', 'Synthetic', 'text'],
    ['personal.social-security-number', '000-12-3456', 'text'],
    ['personal.phone-number', '202-555-0142', 'text'],
    ['personal.alternate-phone', '202-555-0143', 'text'],
    ['personal.secondary-phone', '202-555-0144', 'text'],
    ['personal.email', 'synthetic@example.invalid', 'text'],
    ['language.preferred-language', 'Example Language', 'text'],
    ['language.can-speak-and-understand-english', true, 'boolean'],
    ['language.can-read-simple-english-messages', false, 'boolean'],
    ['language.can-write-simple-english-messages', false, 'boolean'],
    ['language.can-read-simple-messages-in-preferred-language', true, 'boolean'],
    ['language.can-write-simple-messages-in-preferred-language', true, 'boolean'],
    ['security-questions.mother-first-name', 'Example', 'text'],
    ['security-questions.mother-maiden-name', 'Fiction', 'text'],
    ['security-questions.father-first-name', 'Sample', 'text'],
    ['security-questions.father-last-name', 'Example', 'text'],
    ['security-questions.other-legal-representative', null, 'text'],
    ['vitals.height-feet', '5', 'text'],
    ['vitals.height-inches', '8', 'text'],
    ['vitals.weight-pounds', '150', 'text'],
    ['birth.date-of-birth', '2000-01-02', 'date', 'day'],
    ['birth.city-of-birth', 'Example City', 'text'],
    ['birth.state-of-birth', 'Example State', 'text'],
    ['birth.country-of-birth', 'Example Country', 'text'],
    ['address.mailing-address-street-address', '123 Fictional Lane', 'text'],
    ['address.mailing-address-city', 'Sample City', 'text'],
    ['address.mailing-address-state', 'EX', 'text'],
    ['address.mailing-address-zipcode', '00000', 'text'],
    ['address.physical-address-street-address', '456 Fictional Avenue', 'text'],
    ['address.physical-address-street-address-2', 'Unit Example', 'text'],
    ['address.physical-address-city', 'Another City', 'text'],
    ['address.physical-address-state', 'FX', 'text'],
    ['address.physical-address-zipcode', '11111', 'text'],
    ['disability.onset-date-of-disability', '2020-03', 'date', 'month'],
    ['employment.when-did-you-last-work', '2020-02', 'date', 'month'],
  ];
  return { schema: 'packard.intake-client-profile', schemaVersion: '3.0.0', fields: values.map(([id, value, dataType, precision = null]) => ({ id, definitionId: id, recordId: null, value, dataType, precision, readiness: value === null ? 'blocked' : 'ready', blockingReasons: value === null ? [{ code: 'missing' }] : [] })) };
}
