export const IDENTITY_REASONS=Object.freeze([
 'TARGET_RECORD_INVALID','ATTESTATION_ID_MISMATCH','ATTESTATION_CONFIRMATION_INVALID',
 'ATTESTATION_HOST_INVALID','ATTESTATION_TIME_INVALID','ATTESTATION_FUTURE','ATTESTATION_EXPIRED','ATTESTATION_WINDOW_INVALID',
 'ENVIRONMENT_MISMATCH','ORIGIN_MISMATCH','URL_MISSING','URL_MALFORMED','URL_COPY_FORMAT_INVALID','URL_PROTOCOL_INVALID',
 'URL_CREDENTIAL_FIELDS_MISSING','URL_DATABASE_PATH_INVALID','URL_PORT_FORBIDDEN','URL_PARAMETER_DUPLICATE',
 'URL_SSLMODE_INVALID','URL_CHANNEL_BINDING_INVALID','URL_PARAMETER_FORBIDDEN','URL_HOST_INVALID','URL_ENDPOINT_MISMATCH',
 'URL_POLICY_REJECTED','DATABASE_NAME_MISMATCH','POOLING_FORBIDDEN','HOSTNAME_MISMATCH','IDENTITY_CHECK_FAILED'
]);
class IdentityError extends Error {constructor(reason){super('IDENTITY_CHECK_FAILED');this.reason=IDENTITY_REASONS.includes(reason)?reason:'IDENTITY_CHECK_FAILED';}}
export const rejectIdentity=reason=>{throw new IdentityError(reason);};
// Never forward a driver/parser/file error message, code, stack or input value.
export const identityReason=error=>error instanceof IdentityError&&IDENTITY_REASONS.includes(error.reason)?error.reason:'IDENTITY_CHECK_FAILED';
